name: master

on: 
  workflow_dispatch:
    inputs:
      function_name:
        type: choice
        description: 'Select Code to Run'
        options:
        - Hello World
        - Addition Code
        required: true
jobs:         
  trigger_workflows_1:
    name: Run Hello World
    uses: ./.github/workflows/run_python_code_hello_world.yml

  trigger_workflows_2:
    name: Run Addition
    uses: ./.github/workflows/run_python_code_addition.yml

